@startuml


  namespace controller {
      class controller.GameController {
      }
    }
  

  namespace controller {
      class controller.MainController {
      }
    }
  

  namespace controller {
      class controller.MenuController {
      }
    }
  

  namespace model {
      abstract class model.Bug {
      }
    }
  

  namespace model {
      class model.BugsCreator {
      }
    }
  

  namespace model {
      class model.Butterfly {
      }
    }
  

  namespace model {
      class model.Cockroach {
      }
    }
  

  namespace model {
      class model.Fly {
      }
    }
  

  namespace model {
      class model.GameModel {
      }
    }
  

  namespace model {
      class model.Ladybug {
      }
    }
  

  namespace model {
      class model.Wasp {
      }
    }
  

  namespace view {
      class view.GamePanel {
      }
    }
  

 namespace view {
      class view.HUDPanel {
      }
    }
  

  namespace view {
      class view.MainView {
      }
    }
  

  namespace view {
      class view.MenuPanel {
      }
    }
  

  namespace view {
      class view.PausePanel {
      }
    }
  

  namespace view {
      class view.Swatter {
      }
    }
  

  controller.GameController o-- model.BugsCreator : bugsCreator
  controller.GameController o-- model.Bug : bugs
  controller.GameController o-- model.GameModel : gameModel
  controller.GameController o-- view.GamePanel : gamePanel
  controller.GameController o-- view.HUDPanel : hudPanel
  controller.GameController o-- controller.MainController : mainController
  controller.MainController o-- controller.GameController : gameController
  controller.MainController o-- view.GamePanel : gamePanel
  controller.MainController o-- view.HUDPanel : hudPanel
  controller.MainController o-- view.MainView : mainView
  controller.MainController o-- controller.MenuController : menuController
  controller.MainController o-- view.MenuPanel : menuPanel
  controller.MainController o-- view.PausePanel : pausePanel
  controller.MenuController o-- controller.MainController : mainController
  model.Butterfly -up-|> model.Bug
  model.Cockroach -up-|> model.Bug
  model.Fly -up-|> model.Bug
  model.Ladybug -up-|> model.Bug
  model.Wasp -up-|> model.Bug
  view.GamePanel o-- controller.GameController : gameController
  view.GamePanel o-- model.Bug : bugs
  view.MainView o-- view.Swatter : swatter


@enduml
