@startuml

  namespace utilities {
      enum Direction {
        EAST
        NORTH
        NORTHEAST
        NORTHWEST
        SOUTH
        SOUTHEAST
        SOUTHWEST
        WEST
      }
    }
  

  namespace utilities {
      class utilities.ImagesList {
          {static} - BUTTERFLY_1 : ImageIcon
          {static} - BUTTERFLY_2 : ImageIcon
          {static} - BUTTERFLY_3 : ImageIcon
          {static} - BUTTERFLY_4 : ImageIcon
          {static} - COCKROACH_1 : ImageIcon
          {static} - COCKROACH_2 : ImageIcon
          {static} - COCKROACH_3 : ImageIcon
          {static} - COCKROACH_4 : ImageIcon
          {static} - COCKROACH_5 : ImageIcon
          {static} - COCKROACH_6 : ImageIcon
          {static} - FLY_1 : ImageIcon
          {static} - FLY_2 : ImageIcon
          {static} - FLY_3 : ImageIcon
          {static} - LADYBUG_1 : ImageIcon
          {static} - LADYBUG_2 : ImageIcon
          {static} - LADYBUG_3 : ImageIcon
          {static} - LADYBUG_4 : ImageIcon
          {static} - LADYBUG_5 : ImageIcon
          {static} - WASP_1 : ImageIcon
          {static} - WASP_2 : ImageIcon
          {static} + getImage()
          {static} + preloadImages()
      }
    }
  

  namespace utilities {
      class utilities.Utilities {
          {static} - musicClip : Clip
          {static} + playEffects()
          {static} + playMusic()
          {static} + readImage()
          {static} + readNumber()
          {static} + stopMusic()
          {static} + writeNumber()
      }
    }


@enduml
