@startuml

namespace controller {
      class controller.GameController {
          - createNewBug : boolean
          - timer : Timer
          - timerCreators : ArrayList<Timer>
          + GameController()
          + createTimers()
          + doOneLoop()
          + exitGame()
          + handleClick()
          + handleTimer()
          + initializeGame()
          + isEffectsEnable()
          + isMusicEnable()
          + pauseGame()
          + playEffects()
          + playMusic()
          + resumeGame()
          + setEffectsEnable()
          + setMusicEnable()
          + stopMusic()
          + update()
      }
    }
  

 namespace controller {
      class controller.MainController {
          - highScore : int
          + MainController()
          + getGameController()
          + getGamePanel()
          + getHighScore()
          + getHudPanel()
          + nextCursor()
          + pauseGame()
          + readHighScore()
          + resumeGame()
          + setHighScore()
          + setNormalSwatter()
          + setSwatSwatter()
          + startGame()
          + startMenu()
          + updateHighScore()
      }
    }
  

  namespace controller {
      class controller.MenuController {
          - difficulty : int
          - effectsEnable : boolean
          - musicEnable : boolean
          + MenuController()
          + getDifficulty()
          + isEffectsEnable()
          + isMusicEnable()
          + playEffects()
          + setDifficulty()
          + setEffectsEnable()
          + setMusicEnable()
          + startGame()
      }
    }
  

  controller.GameController o-- model.BugsCreator : bugsCreator
  controller.GameController o-- model.GameModel : gameModel
  controller.GameController o-- model.Bug : bugs
  controller.GameController o-- controller.MainController : mainController
  controller.MainController o-- controller.GameController : gameController
  controller.MainController o-- view.MainView : mainView
  controller.MainController o-- controller.MenuController : menuController
  controller.MenuController o-- controller.MainController : mainController




@enduml
