@startuml
'https://plantuml.com/activity-diagram-beta

(*)  --> "Bug.move() è chiamato da update() di GameController"
--> "L'insetto si muove aumentando e/o diminuendo le proprie coordinate con la velocità di movimento"
If "L'insetto si trova sul bordo" then
--> [Si] "Viene richiamato il metodo changeDirectionBorder()"
--> "La sua direzione cambia in quella opposta al bordo in cui si trova"
else
--> [No] "Viene richiamato il metodo changeDirection()"
--> "A seconda della direzione in cui si trova l'insetto,
questo dovrà cambiarla in una delle tre direzioni adiacenti "
Endif


@enduml
