@startuml
'https://plantuml.com/activity-diagram-beta

(*)  --> "Si richiede un focus sul GamePanel"
--> "Si chiama il metodo update()"
-->"Prende le coordinate del mouse"
-->"Comanda ogni Bug di aggiornare le sue coordinate"
-->"Viene richiamato il metodo handleTimer()"
-->"Viene chiesto alla Swatter di passare al frame successivo"
-->"Viene richiesto al GamePanel e all'HUDPanel di aggiornarsi"


@enduml
